import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import QueryProvider from "@/components/providers/query-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "GepukJom - Best Ayam Gepuk Directory in Malaysia",
	description: "Generated by create next app",
	metadataBase: new URL("https://gepukjom.nrmnqdds.com"),
	keywords: [
		"gepukjom",
		"ayam gepuk",
		"ayam gepuk jom",
		"ayam gepuk malaysia",
		"ayam gepuk directory",
		"ayam gepuk restaurant",
		"ayam gepuk food",
	],
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="scroll-smooth font-geist">
				<ThemeProvider attribute="class" defaultTheme="dark">
					<QueryProvider>
						<Navbar />
						{children}
						<Footer />
					</QueryProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
