import Navbar from "@/components/navbar";
import { ThemeProvider } from "@/components/providers/theme-provider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "GepukJom - Best Ayam Gepuk Directory in Malaysia",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="scroll-smooth font-geist">
				<ThemeProvider attribute="class" defaultTheme="dark">
					<Navbar />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
