import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import QueryProvider from "@/components/providers/query-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "GepukJom - Best Ayam Gepuk Directory in Malaysia",
	description: "Generated by create next app",
	icons: {
		icon: "/gepukjom.svg",
		shortcut: "/gepukjom.svg",
		apple: "/gepukjom.svg",
		other: {
			rel: "icon",
			url: "/gepukjom.svg",
		},
	},
	metadataBase: new URL("https://gepukjom.nrmnqdds.com"),
	keywords: [
		"gepukjom",
		"ayam gepuk",
		"ayam gepuk jom",
		"ayam gepuk malaysia",
		"ayam gepuk directory",
		"ayam gepuk restaurant",
		"ayam gepuk food",
	],
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className="scroll-smooth font-geist antialiased">
					<ThemeProvider attribute="class" defaultTheme="dark">
						<QueryProvider>
							<Navbar />
							<main className="bg-background w-full min-h-screen relative isolate p-24 sm:p-32 lg:p-40">
								{children}
							</main>
							<Toaster />
							<Footer />
						</QueryProvider>
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
