name: Deploy to Amplify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli

      - name: Configure Amplify
        run: amplify configure  # This step might require some interactive setup

      - name: Deploy to Amplify
        run: amplify publish